<!DOCTYPE html>
<html lang="en">
<!--[if IE 9 ]><html class="ie9"><![endif]-->
<body>
<!-- Page Loader -->
<div id="page-loader">
    <div class="preloader preloader--xl preloader--light">
        <svg viewbox="25 25 50 50">
            <circle cx="50" cy="50" r="20"></circle>
        </svg>
    </div>
</div>
<!-- Header -->
<header id="header">
    <div class="logo">
        <a href="#" class="hidden-xs">
            Kilo Store
            <small>Administrador de Productos</small>
        </a>
        <i class="logo__trigger zmdi zmdi-menu" data-mae-action="block-open" data-mae-target="#navigation"></i>
    </div>
<!--MEnú de usuario Superior-->
    <ul class="top-menu">
        <li class="top-menu__trigger hidden-lg hidden-md">
            <a href=""><i class="zmdi zmdi-search"></i></a>
        </li>
        <li class="dropdown hidden-xs">
            <a data-toggle="dropdown" href=""><i class="zmdi zmdi-more-vert"></i></a>
            <ul class="dropdown-menu dropdown-menu--icon pull-right">
                <li>
                    <a data-mae-action="clear-localstorage" href=""><i class="zmdi zmdi-delete"></i>Productos</a>
                </li>
                <li>
                    <a href=""><i class="zmdi zmdi-face"></i>Información Usuario</a>
                </li>
                <li>
                    <a href="<?php echo $this->basePath().'login';?>"><i class="zmdi zmdi-settings"></i>Cerrar Sesión</a>
                </li>
            </ul>
        </li>
</header>
<!-- Menú Lateral-->
<section id="main">
    <aside id="navigation">
        <div class="navigation__header">
            <i class="zmdi zmdi-long-arrow-left" data-mae-action="block-close"></i>
        </div>
        <div class="navigation__menu c-overflow">
            <ul>
                <li>
                    <a href="<?php echo $this->basePath().'catalogo';?>"><i class="zmdi zmdi-home"></i> Inicio </a>
                </li>
                <li><a href="<?php echo $this->basePath().' tiendas';?>"><i class="zmdi zmdi-layers"></i> Tiendas </a></li>
            </ul>
        </div>
    </aside>
<!--Data table By jsm-->
    <section id="content">
        <div class="content__header tab-content">
            <h2>Catálogo</h2>
        </div>
        <div class="card">
            <div class="card__header">
                <h2>Existencia de Productos<small>A continuacion se muestra un catalogo de los productos en tienda</small></h2>
            </div>
            <div class="card__body">
                <div class="table-responsive">
                    <table id="jsontable" class="table-striped">
                        <thead>
                        <tr>
                            <th>Clave Producto</th>
                            <th>Nombre Producto</th>
                            <th>Tienda</th>
                            <th>Precio</th>
                            <th>Existencias</th>
                        </tr>
                        </thead>
                        <div>
                        </div>
                    </table>
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card__header">
                <h2>Agregar Producto</h2>
            </div>

            <div class="card__body"  >
                <form role="form" id="producto" method="post">
                    <div class="form-group" >
                        <input type="text" name="datos[nombre_producto]"class="form-control" placeholder="Nombre del Producto">
                        <i class="form-group__bar"></i>
                    </div>
                    <div class="form-group">
                        <input id="campo" type="text" maxlength="4" name="datos[clave_producto]"class="form-control" placeholder="Clave del producto" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" >
                        <i class="form-group__bar"></i>
                    </div>
                    <div class="form-group">
                        <input id="campo" type="text" name="datos[precio_producto]" class="form-control" placeholder="Precio de venta $MXN" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" >
                        <i class="form-group__bar"></i>
                    </div>
                    <div class="form-group">
                        <input type="text" name="datos[datos_producto]" class="form-control" placeholder="Descripción    ">
                        <i class="form-group__bar"></i>
                    </div>
                    <div class="form-group">
                        <input type="text" name="datos[existencias]" class="form-control" placeholder="Cantidad a agregar">
                        <i class="form-group__bar"></i>
                    </div>
                    <br>
                    <input id="producto" type="submit" class="btn btn-primary" name="Guardar" value="Iniciar">
                </form>
            </div>
        </div>

    </section>

    <footer id="footer">
        Copyright &copy; 2017 KiloStore Josué Saúl Martínez
        <ul class="footer__menu">
            <li><a href="">Home</a></li>
        </ul>
    </footer>
</section>

<!-- Older IE Warning -->
<!--[if lt IE 9]>
<div class="ie-warning">
    <h1>Warning!!</h1>
    <p>You are using an outdated version of Internet Explorer, please upgrade <br/>to any of the following web browsers to access this website.</p>
    <div class="ie-warning__container">
        <ul class="ie-warning__download">
            <li>
                <a href="http://www.google.com/chrome/">
                    <img src="img/browsers/chrome.png" alt="">
                    <div>Chrome</div>
                </a>
            </li>
            <li>
                <a href="https://www.mozilla.org/en-US/firefox/new/">
                    <img src="img/browsers/firefox.png" alt="">
                    <div>Firefox</div>
                </a>
            </li>
            <li>
                <a href="http://www.opera.com">
                    <img src="img/browsers/opera.png" alt="">
                    <div>Opera</div>
                </a>
            </li>
            <li>
                <a href="https://www.apple.com/safari/">
                    <img src="img/browsers/safari.png" alt="">
                    <div>Safari</div>
                </a>
            </li>
            <li>
                <a href="http://windows.microsoft.com/en-us/internet-explorer/download-ie">
                    <img src="img/browsers/ie.png" alt="">
                    <div>IE (New)</div>
                </a>
            </li>
        </ul>
    </div>
</div>
<![endif]-->


<!-- Javascript Libraries -->

<!-- jQuery -->
<script src="vendors\bower_components\jquery\dist\jquery.min.js"></script>

<!-- Bootstrap -->
<script src="vendors\bower_components\bootstrap\dist\js\bootstrap.min.js"></script>

<!-- Malihu ScrollBar -->
<script src="vendors\bower_components\malihu-custom-scrollbar-plugin\jquery.mCustomScrollbar.concat.min.js"></script>

<!-- Bootstrap Notify -->
<script src="vendors\bower_components\remarkable-bootstrap-notify\dist\bootstrap-notify.min.js"></script>

<!-- Bootgrid -->
<script src="vendors\bower_components\jquery.bootgrid\dist\jquery.bootgrid.min.js"></script>
<!-- Placeholder for IE9 -->
<!--[if IE 9 ]>
<script src="vendors/bower_components/jquery-placeholder/jquery.placeholder.min.js"></script>
<![endif]-->
<!-- Site Functions & Actions -->
<script src="js\app.min.js"></script>
</body>
</html>