<!-- Este bloque pertenece a un login sencillo -->
<div class="card">
    <div class="card__header">
        <h2>Iniciar Session<small>
            </small></h2>
    </div>
    <div class="card__body">
        <form role="form" id="login-submit" method="post">
            <div class="form-group">
                <input type="email" class="form-control" name="datos[e_mail]" placeholder="Ingresa tu correo corporativo" >
                <i class="form-group__bar"></i>
            </div>
            <div class="form-group">
                <input type="password" class="form-control" name="datos[password]" placeholder="Contraseña">
                <i class="form-group__bar"></i>
            </div>

            <br>

            <input id="login-submit" type="submit" class="btn btn-default" name="Iniciar" value="Iniciar">
        </form>
    </div>
</div>